#!/bin/sh
echo "Launching ElectrumXBTE server..."
USERNAME=$(envdir ./env printenv USERNAME)
ELECTRUMXBTE=$(envdir ./env printenv ELECTRUMXBTE)
ulimit -n 4000 && exec 2>&1 envdir ./env envuidgid $USERNAME python3 $ELECTRUMXBTE
